### ISSUE TITLE
Log submission page

### ISSUE THREAD

**Issue by thxo** [young-amateurs-rc/contest-manager#4]
* Enter basic information and categories as defined in rules.
* Upload Cabrillo.
* Along the way, a storage mechanism should be figured out.

**Comment by galengold** [comment]
Options for log storage:
1. As files, with a filename reference in the database. Pastebox input is written to a file during submission
2. As text, with the text stored in the database. Upload input is exctracted as text and entered into the database.

**Comment by wubcrow** [comment]
I'll take on this. Thanks for building the front-end prototype.

I think when this is actually finished the categories would end up being just a single drop-down list.

**Comment by galengold** [comment]
having the questionnaire is good for getting the correct category, but it would be hard for it to be extensible.

**Comment by galengold** [comment]
cabrillo parsing (global)
contest validation
scoring

the first 2 need to pass before accepting a submission, the 3rd shouldn't be done until the log due date has passed because they need to be cross-referenced. validation and scoring can just be the 2 components of a contest plugin.
we can also use client-side validation for the demographic fields

**Comment by galengold** [comment]
allow multiple submissions. append a timestamp to the callsign in log filename and database entry for deduplication. #15 will allow for the admin to choose which version to score.

**Comment by galengold** [comment]
closing with merge of #19
